### ISSUE TITLE
Tasks to do before 0.7

### ISSUE THREAD

**Issue by ptiede** [ptiede/Comrade.jl#252]
Here is a list of things I need to do before releasing 0.7

- [x] Add polarization tests (#229 )
- [x] Add jones matrix and RIME tests 
- [x] Add missing data checks for coherency matrices (partially handled in VLBILikelihoods 0.1.2 but needs testing)
- [x] Fix docs to use new formalism (#188)
- [x] Add polarization example to the docs (#188)
- [x] Fix all examples to use new formalism (#188)
- [x] Fix all library packages to match new 0.7 formalism (#254 )
- [x] Improve test coverage to a minimum of 85% 
- [x] Add conventions page
- [x] Remove unnecessary dependencies (#253)
- [x] Find slowdown (#261)
- [x] Add relative or transitional gain model (#264)
