### ISSUE TITLE
Roadmap to 0.11

### ISSUE THREAD

**Issue by ptiede** [ptiede/Comrade.jl#341]
- [ ]  Rework data format and data layout to make it easier to handle multifrequency and time-dependent models
- [x]  Change the instrument model format so you only specify the cache once and allow for easier tracking of different instrument terms
- [x]  rename visibilities to visilibilitymap and embrace the grid system.
